/*
 * generated by Xtext 2.20.0
 */
package mdsd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathInterpeterStandaloneSetup extends MathInterpeterStandaloneSetupGenerated {

	public static void doSetup() {
		new MathInterpeterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
