/*
 * generated by Xtext 2.20.0
 */
package mdsd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathInterpeterScopeProvider extends DelegatingScopeProvider {
}
