/**
 * generated by Xtext 2.20.0
 */
package mdsd.mathInterpeter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.mathInterpeter.MathInterpeterPackage#getExp()
 * @model
 * @generated
 */
public interface Exp extends EObject
{
} // Exp
