/**
 * generated by Xtext 2.20.0
 */
package mdsd.mathInterpeter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.mathInterpeter.MathInterpeterPackage#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends Exp
{
} // Primary
