/**
 * generated by Xtext 2.20.0
 */
package mdsd.mathInterpeter.impl;

import mdsd.mathInterpeter.MathInterpeterPackage;
import mdsd.mathInterpeter.Primary;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrimaryImpl extends ExpImpl implements Primary
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimaryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathInterpeterPackage.Literals.PRIMARY;
  }

} //PrimaryImpl
