/*
 * generated by Xtext 2.20.0
 */
package mdsd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMathInterpeterValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mdsd.mathInterpeter.MathInterpeterPackage.eINSTANCE);
		return result;
	}
}
