/*
 * generated by Xtext 2.20.0
 */
package mdsd.parser.antlr;

import com.google.inject.Inject;
import mdsd.parser.antlr.internal.InternalMathInterpeterParser;
import mdsd.services.MathInterpeterGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MathInterpeterParser extends AbstractAntlrParser {

	@Inject
	private MathInterpeterGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathInterpeterParser createParser(XtextTokenStream stream) {
		return new InternalMathInterpeterParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MathExp";
	}

	public MathInterpeterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathInterpeterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
